[
{ "tag": "typedef", "ns": 0, "name": "int8_t", "location": "/usr/include/stdint.h:36:22", "type": { "tag": ":signed-char" } },
{ "tag": "typedef", "ns": 0, "name": "int16_t", "location": "/usr/include/stdint.h:37:20", "type": { "tag": ":short" } },
{ "tag": "typedef", "ns": 0, "name": "int32_t", "location": "/usr/include/stdint.h:38:15", "type": { "tag": ":int" } },
{ "tag": "typedef", "ns": 0, "name": "int64_t", "location": "/usr/include/stdint.h:43:24", "type": { "tag": ":long-long" } },
{ "tag": "typedef", "ns": 0, "name": "uint8_t", "location": "/usr/include/stdint.h:48:24", "type": { "tag": ":unsigned-char" } },
{ "tag": "typedef", "ns": 0, "name": "uint16_t", "location": "/usr/include/stdint.h:49:28", "type": { "tag": ":unsigned-short" } },
{ "tag": "typedef", "ns": 0, "name": "uint32_t", "location": "/usr/include/stdint.h:51:23", "type": { "tag": ":unsigned-int" } },
{ "tag": "typedef", "ns": 0, "name": "uint64_t", "location": "/usr/include/stdint.h:58:32", "type": { "tag": ":unsigned-long-long" } },
{ "tag": "typedef", "ns": 0, "name": "int_least8_t", "location": "/usr/include/stdint.h:65:22", "type": { "tag": ":signed-char" } },
{ "tag": "typedef", "ns": 0, "name": "int_least16_t", "location": "/usr/include/stdint.h:66:20", "type": { "tag": ":short" } },
{ "tag": "typedef", "ns": 0, "name": "int_least32_t", "location": "/usr/include/stdint.h:67:15", "type": { "tag": ":int" } },
{ "tag": "typedef", "ns": 0, "name": "int_least64_t", "location": "/usr/include/stdint.h:72:24", "type": { "tag": ":long-long" } },
{ "tag": "typedef", "ns": 0, "name": "uint_least8_t", "location": "/usr/include/stdint.h:76:24", "type": { "tag": ":unsigned-char" } },
{ "tag": "typedef", "ns": 0, "name": "uint_least16_t", "location": "/usr/include/stdint.h:77:28", "type": { "tag": ":unsigned-short" } },
{ "tag": "typedef", "ns": 0, "name": "uint_least32_t", "location": "/usr/include/stdint.h:78:23", "type": { "tag": ":unsigned-int" } },
{ "tag": "typedef", "ns": 0, "name": "uint_least64_t", "location": "/usr/include/stdint.h:83:32", "type": { "tag": ":unsigned-long-long" } },
{ "tag": "typedef", "ns": 0, "name": "int_fast8_t", "location": "/usr/include/stdint.h:90:22", "type": { "tag": ":signed-char" } },
{ "tag": "typedef", "ns": 0, "name": "int_fast16_t", "location": "/usr/include/stdint.h:96:15", "type": { "tag": ":int" } },
{ "tag": "typedef", "ns": 0, "name": "int_fast32_t", "location": "/usr/include/stdint.h:97:15", "type": { "tag": ":int" } },
{ "tag": "typedef", "ns": 0, "name": "int_fast64_t", "location": "/usr/include/stdint.h:99:24", "type": { "tag": ":long-long" } },
{ "tag": "typedef", "ns": 0, "name": "uint_fast8_t", "location": "/usr/include/stdint.h:103:24", "type": { "tag": ":unsigned-char" } },
{ "tag": "typedef", "ns": 0, "name": "uint_fast16_t", "location": "/usr/include/stdint.h:109:23", "type": { "tag": ":unsigned-int" } },
{ "tag": "typedef", "ns": 0, "name": "uint_fast32_t", "location": "/usr/include/stdint.h:110:23", "type": { "tag": ":unsigned-int" } },
{ "tag": "typedef", "ns": 0, "name": "uint_fast64_t", "location": "/usr/include/stdint.h:112:32", "type": { "tag": ":unsigned-long-long" } },
{ "tag": "typedef", "ns": 0, "name": "intptr_t", "location": "/usr/include/stdint.h:125:15", "type": { "tag": ":int" } },
{ "tag": "typedef", "ns": 0, "name": "uintptr_t", "location": "/usr/include/stdint.h:128:23", "type": { "tag": ":unsigned-int" } },
{ "tag": "typedef", "ns": 0, "name": "intmax_t", "location": "/usr/include/stdint.h:138:24", "type": { "tag": ":long-long" } },
{ "tag": "typedef", "ns": 0, "name": "uintmax_t", "location": "/usr/include/stdint.h:140:32", "type": { "tag": ":unsigned-long-long" } },
{ "tag": "struct", "ns": 0, "name": "tb_cell", "id": 0, "location": "/usr/include/termbox.h:135:8", "bit-size": 64, "bit-alignment": 32, "fields": [{ "tag": "field", "name": "ch", "bit-offset": 0, "bit-size": 32, "bit-alignment": 32, "type": { "tag": "uint32_t" } }, { "tag": "field", "name": "fg", "bit-offset": 32, "bit-size": 16, "bit-alignment": 16, "type": { "tag": "uint16_t" } }, { "tag": "field", "name": "bg", "bit-offset": 48, "bit-size": 16, "bit-alignment": 16, "type": { "tag": "uint16_t" } }] },
{ "tag": "struct", "ns": 0, "name": "tb_event", "id": 0, "location": "/usr/include/termbox.h:150:8", "bit-size": 192, "bit-alignment": 32, "fields": [{ "tag": "field", "name": "type", "bit-offset": 0, "bit-size": 8, "bit-alignment": 8, "type": { "tag": "uint8_t" } }, { "tag": "field", "name": "mod", "bit-offset": 8, "bit-size": 8, "bit-alignment": 8, "type": { "tag": "uint8_t" } }, { "tag": "field", "name": "key", "bit-offset": 16, "bit-size": 16, "bit-alignment": 16, "type": { "tag": "uint16_t" } }, { "tag": "field", "name": "ch", "bit-offset": 32, "bit-size": 32, "bit-alignment": 32, "type": { "tag": "uint32_t" } }, { "tag": "field", "name": "w", "bit-offset": 64, "bit-size": 32, "bit-alignment": 32, "type": { "tag": "int32_t" } }, { "tag": "field", "name": "h", "bit-offset": 96, "bit-size": 32, "bit-alignment": 32, "type": { "tag": "int32_t" } }, { "tag": "field", "name": "x", "bit-offset": 128, "bit-size": 32, "bit-alignment": 32, "type": { "tag": "int32_t" } }, { "tag": "field", "name": "y", "bit-offset": 160, "bit-size": 32, "bit-alignment": 32, "type": { "tag": "int32_t" } }] },
{ "tag": "function", "name": "tb_init", "location": "/usr/include/termbox.h:174:15", "variadic": false, "inline": false, "storage_class": "none", "parameters": [], "return-type": { "tag": ":int" } },
{ "tag": "function", "name": "tb_shutdown", "location": "/usr/include/termbox.h:175:16", "variadic": false, "inline": false, "storage_class": "none", "parameters": [], "return-type": { "tag": ":void" } },
{ "tag": "function", "name": "tb_width", "location": "/usr/include/termbox.h:183:15", "variadic": false, "inline": false, "storage_class": "none", "parameters": [], "return-type": { "tag": ":int" } },
{ "tag": "function", "name": "tb_height", "location": "/usr/include/termbox.h:184:15", "variadic": false, "inline": false, "storage_class": "none", "parameters": [], "return-type": { "tag": ":int" } },
{ "tag": "function", "name": "tb_clear", "location": "/usr/include/termbox.h:189:16", "variadic": false, "inline": false, "storage_class": "none", "parameters": [], "return-type": { "tag": ":void" } },
{ "tag": "function", "name": "tb_set_clear_attributes", "location": "/usr/include/termbox.h:190:16", "variadic": false, "inline": false, "storage_class": "none", "parameters": [{ "tag": "parameter", "name": "fg", "type": { "tag": "uint16_t" } }, { "tag": "parameter", "name": "bg", "type": { "tag": "uint16_t" } }], "return-type": { "tag": ":void" } },
{ "tag": "function", "name": "tb_present", "location": "/usr/include/termbox.h:193:16", "variadic": false, "inline": false, "storage_class": "none", "parameters": [], "return-type": { "tag": ":void" } },
{ "tag": "function", "name": "tb_set_cursor", "location": "/usr/include/termbox.h:201:16", "variadic": false, "inline": false, "storage_class": "none", "parameters": [{ "tag": "parameter", "name": "cx", "type": { "tag": ":int" } }, { "tag": "parameter", "name": "cy", "type": { "tag": ":int" } }], "return-type": { "tag": ":void" } },
{ "tag": "function", "name": "tb_put_cell", "location": "/usr/include/termbox.h:206:16", "variadic": false, "inline": false, "storage_class": "none", "parameters": [{ "tag": "parameter", "name": "x", "type": { "tag": ":int" } }, { "tag": "parameter", "name": "y", "type": { "tag": ":int" } }, { "tag": "parameter", "name": "cell", "type": { "tag": ":pointer", "type": { "tag": ":struct", "name": "tb_cell", "id": 1 } } }], "return-type": { "tag": ":void" } },
{ "tag": "function", "name": "tb_change_cell", "location": "/usr/include/termbox.h:207:16", "variadic": false, "inline": false, "storage_class": "none", "parameters": [{ "tag": "parameter", "name": "x", "type": { "tag": ":int" } }, { "tag": "parameter", "name": "y", "type": { "tag": ":int" } }, { "tag": "parameter", "name": "ch", "type": { "tag": "uint32_t" } }, { "tag": "parameter", "name": "fg", "type": { "tag": "uint16_t" } }, { "tag": "parameter", "name": "bg", "type": { "tag": "uint16_t" } }], "return-type": { "tag": ":void" } },
{ "tag": "function", "name": "tb_blit", "location": "/usr/include/termbox.h:215:16", "variadic": false, "inline": false, "storage_class": "none", "parameters": [{ "tag": "parameter", "name": "x", "type": { "tag": ":int" } }, { "tag": "parameter", "name": "y", "type": { "tag": ":int" } }, { "tag": "parameter", "name": "w", "type": { "tag": ":int" } }, { "tag": "parameter", "name": "h", "type": { "tag": ":int" } }, { "tag": "parameter", "name": "cells", "type": { "tag": ":pointer", "type": { "tag": ":struct", "name": "tb_cell", "id": 1 } } }], "return-type": { "tag": ":void" } },
{ "tag": "function", "name": "tb_cell_buffer", "location": "/usr/include/termbox.h:222:27", "variadic": false, "inline": false, "storage_class": "none", "parameters": [], "return-type": { "tag": ":pointer", "type": { "tag": ":struct", "name": "tb_cell", "id": 1 } } },
{ "tag": "function", "name": "tb_select_input_mode", "location": "/usr/include/termbox.h:247:15", "variadic": false, "inline": false, "storage_class": "none", "parameters": [{ "tag": "parameter", "name": "mode", "type": { "tag": ":int" } }], "return-type": { "tag": ":int" } },
{ "tag": "function", "name": "tb_select_output_mode", "location": "/usr/include/termbox.h:290:15", "variadic": false, "inline": false, "storage_class": "none", "parameters": [{ "tag": "parameter", "name": "mode", "type": { "tag": ":int" } }], "return-type": { "tag": ":int" } },
{ "tag": "function", "name": "tb_peek_event", "location": "/usr/include/termbox.h:297:15", "variadic": false, "inline": false, "storage_class": "none", "parameters": [{ "tag": "parameter", "name": "event", "type": { "tag": ":pointer", "type": { "tag": ":struct", "name": "tb_event", "id": 2 } } }, { "tag": "parameter", "name": "timeout", "type": { "tag": ":int" } }], "return-type": { "tag": ":int" } },
{ "tag": "function", "name": "tb_poll_event", "location": "/usr/include/termbox.h:303:15", "variadic": false, "inline": false, "storage_class": "none", "parameters": [{ "tag": "parameter", "name": "event", "type": { "tag": ":pointer", "type": { "tag": ":struct", "name": "tb_event", "id": 2 } } }], "return-type": { "tag": ":int" } },
{ "tag": "function", "name": "tb_utf8_char_length", "location": "/usr/include/termbox.h:307:15", "variadic": false, "inline": false, "storage_class": "none", "parameters": [{ "tag": "parameter", "name": "c", "type": { "tag": ":char" } }], "return-type": { "tag": ":int" } },
{ "tag": "function", "name": "tb_utf8_char_to_unicode", "location": "/usr/include/termbox.h:308:15", "variadic": false, "inline": false, "storage_class": "none", "parameters": [{ "tag": "parameter", "name": "out", "type": { "tag": ":pointer", "type": { "tag": "uint32_t" } } }, { "tag": "parameter", "name": "c", "type": { "tag": ":pointer", "type": { "tag": ":char" } } }], "return-type": { "tag": ":int" } },
{ "tag": "function", "name": "tb_utf8_unicode_to_char", "location": "/usr/include/termbox.h:309:15", "variadic": false, "inline": false, "storage_class": "none", "parameters": [{ "tag": "parameter", "name": "out", "type": { "tag": ":pointer", "type": { "tag": ":char" } } }, { "tag": "parameter", "name": "c", "type": { "tag": "uint32_t" } }], "return-type": { "tag": ":int" } },
{ "tag": "const", "name": "__GNU_LIBRARY__", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:523:12", "type": { "tag": ":long" }, "value": 6 },
{ "tag": "const", "name": "_SYS_CDEFS_H", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:524:12", "type": { "tag": ":long" }, "value": 1 },
{ "tag": "const", "name": "__GLIBC__", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:525:12", "type": { "tag": ":long" }, "value": 2 },
{ "tag": "const", "name": "TB_KEY_CTRL_5", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:526:12", "type": { "tag": ":long" }, "value": 29 },
{ "tag": "const", "name": "TB_KEY_CTRL_LSQ_BRACKET", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:527:12", "type": { "tag": ":long" }, "value": 27 },
{ "tag": "const", "name": "__GLIBC_MINOR__", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:528:12", "type": { "tag": ":long" }, "value": 21 },
{ "tag": "const", "name": "TB_KEY_CTRL_3", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:529:12", "type": { "tag": ":long" }, "value": 27 },
{ "tag": "const", "name": "TB_KEY_CTRL_4", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:530:12", "type": { "tag": ":long" }, "value": 28 },
{ "tag": "const", "name": "TB_KEY_CTRL_J", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:531:12", "type": { "tag": ":long" }, "value": 10 },
{ "tag": "const", "name": "TB_KEY_CTRL_H", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:532:12", "type": { "tag": ":long" }, "value": 8 },
{ "tag": "const", "name": "TB_KEY_TAB", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:533:12", "type": { "tag": ":long" }, "value": 9 },
{ "tag": "const", "name": "TB_KEY_CTRL_E", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:534:12", "type": { "tag": ":long" }, "value": 5 },
{ "tag": "const", "name": "TB_KEY_CTRL_I", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:535:12", "type": { "tag": ":long" }, "value": 9 },
{ "tag": "const", "name": "TB_KEY_CTRL_BACKSLASH", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:536:12", "type": { "tag": ":long" }, "value": 28 },
{ "tag": "const", "name": "TB_KEY_CTRL_F", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:537:12", "type": { "tag": ":long" }, "value": 6 },
{ "tag": "const", "name": "TB_KEY_BACKSPACE", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:538:12", "type": { "tag": ":long" }, "value": 8 },
{ "tag": "const", "name": "TB_KEY_CTRL_A", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:539:12", "type": { "tag": ":long" }, "value": 1 },
{ "tag": "const", "name": "TB_KEY_CTRL_G", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:540:12", "type": { "tag": ":long" }, "value": 7 },
{ "tag": "const", "name": "TB_KEY_CTRL_2", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:541:12", "type": { "tag": ":long" }, "value": 0 },
{ "tag": "const", "name": "TB_KEY_CTRL_C", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:542:12", "type": { "tag": ":long" }, "value": 3 },
{ "tag": "const", "name": "TB_KEY_CTRL_B", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:543:12", "type": { "tag": ":long" }, "value": 2 },
{ "tag": "const", "name": "__STDC_NO_THREADS__", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:544:12", "type": { "tag": ":long" }, "value": 1 },
{ "tag": "const", "name": "TB_KEY_MOUSE_WHEEL_UP", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:545:12", "type": { "tag": ":long" }, "value": 65509 },
{ "tag": "const", "name": "TB_KEY_MOUSE_RELEASE", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:546:12", "type": { "tag": ":long" }, "value": 65510 },
{ "tag": "const", "name": "TB_KEY_CTRL_TILDE", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:547:12", "type": { "tag": ":long" }, "value": 0 },
{ "tag": "const", "name": "TB_KEY_MOUSE_WHEEL_DOWN", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:548:12", "type": { "tag": ":long" }, "value": 65508 },
{ "tag": "const", "name": "TB_KEY_CTRL_Y", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:549:12", "type": { "tag": ":long" }, "value": 25 },
{ "tag": "const", "name": "TB_KEY_CTRL_X", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:550:12", "type": { "tag": ":long" }, "value": 24 },
{ "tag": "const", "name": "TB_KEY_CTRL_D", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:551:12", "type": { "tag": ":long" }, "value": 4 },
{ "tag": "const", "name": "TB_KEY_CTRL_Z", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:552:12", "type": { "tag": ":long" }, "value": 26 },
{ "tag": "const", "name": "TB_KEY_CTRL_T", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:553:12", "type": { "tag": ":long" }, "value": 20 },
{ "tag": "const", "name": "TB_KEY_CTRL_U", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:554:12", "type": { "tag": ":long" }, "value": 21 },
{ "tag": "const", "name": "TB_KEY_CTRL_S", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:555:12", "type": { "tag": ":long" }, "value": 19 },
{ "tag": "const", "name": "TB_KEY_CTRL_W", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:556:12", "type": { "tag": ":long" }, "value": 23 },
{ "tag": "const", "name": "TB_KEY_CTRL_V", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:557:12", "type": { "tag": ":long" }, "value": 22 },
{ "tag": "const", "name": "TB_KEY_CTRL_P", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:558:12", "type": { "tag": ":long" }, "value": 16 },
{ "tag": "const", "name": "TB_KEY_CTRL_O", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:559:12", "type": { "tag": ":long" }, "value": 15 },
{ "tag": "const", "name": "TB_KEY_ESC", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:560:12", "type": { "tag": ":long" }, "value": 27 },
{ "tag": "const", "name": "TB_KEY_CTRL_R", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:561:12", "type": { "tag": ":long" }, "value": 18 },
{ "tag": "const", "name": "TB_KEY_CTRL_Q", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:562:12", "type": { "tag": ":long" }, "value": 17 },
{ "tag": "const", "name": "TB_KEY_CTRL_L", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:563:12", "type": { "tag": ":long" }, "value": 12 },
{ "tag": "const", "name": "TB_KEY_CTRL_K", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:564:12", "type": { "tag": ":long" }, "value": 11 },
{ "tag": "const", "name": "TB_KEY_CTRL_N", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:565:12", "type": { "tag": ":long" }, "value": 14 },
{ "tag": "const", "name": "TB_KEY_ENTER", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:566:12", "type": { "tag": ":long" }, "value": 13 },
{ "tag": "const", "name": "TB_KEY_CTRL_M", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:567:12", "type": { "tag": ":long" }, "value": 13 },
{ "tag": "const", "name": "TB_KEY_F4", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:568:12", "type": { "tag": ":long" }, "value": 65532 },
{ "tag": "const", "name": "__USE_ISOC95", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:569:12", "type": { "tag": ":long" }, "value": 1 },
{ "tag": "const", "name": "TB_KEY_F5", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:570:12", "type": { "tag": ":long" }, "value": 65531 },
{ "tag": "const", "name": "__USE_ISOC99", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:571:12", "type": { "tag": ":long" }, "value": 1 },
{ "tag": "const", "name": "__USE_ISOC11", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:572:12", "type": { "tag": ":long" }, "value": 1 },
{ "tag": "const", "name": "TB_KEY_F6", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:573:12", "type": { "tag": ":long" }, "value": 65530 },
{ "tag": "const", "name": "TB_KEY_F7", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:574:12", "type": { "tag": ":long" }, "value": 65529 },
{ "tag": "const", "name": "_FEATURES_H", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:575:12", "type": { "tag": ":long" }, "value": 1 },
{ "tag": "const", "name": "_STDINT_H", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:576:12", "type": { "tag": ":long" }, "value": 1 },
{ "tag": "const", "name": "TB_KEY_F1", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:577:12", "type": { "tag": ":long" }, "value": 65535 },
{ "tag": "const", "name": "TB_KEY_F2", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:578:12", "type": { "tag": ":long" }, "value": 65534 },
{ "tag": "const", "name": "TB_KEY_F3", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:579:12", "type": { "tag": ":long" }, "value": 65533 },
{ "tag": "const", "name": "TB_KEY_ARROW_RIGHT", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:580:12", "type": { "tag": ":long" }, "value": 65514 },
{ "tag": "const", "name": "TB_KEY_MOUSE_LEFT", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:581:12", "type": { "tag": ":long" }, "value": 65513 },
{ "tag": "const", "name": "TB_KEY_MOUSE_RIGHT", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:582:12", "type": { "tag": ":long" }, "value": 65512 },
{ "tag": "const", "name": "TB_KEY_MOUSE_MIDDLE", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:583:12", "type": { "tag": ":long" }, "value": 65511 },
{ "tag": "const", "name": "TB_KEY_PGUP", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:584:12", "type": { "tag": ":long" }, "value": 65519 },
{ "tag": "const", "name": "TB_KEY_ARROW_UP", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:585:12", "type": { "tag": ":long" }, "value": 65517 },
{ "tag": "const", "name": "TB_KEY_PGDN", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:586:12", "type": { "tag": ":long" }, "value": 65518 },
{ "tag": "const", "name": "TB_KEY_ARROW_DOWN", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:587:12", "type": { "tag": ":long" }, "value": 65516 },
{ "tag": "const", "name": "TB_KEY_ARROW_LEFT", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:588:12", "type": { "tag": ":long" }, "value": 65515 },
{ "tag": "const", "name": "TB_KEY_INSERT", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:589:12", "type": { "tag": ":long" }, "value": 65523 },
{ "tag": "const", "name": "TB_KEY_DELETE", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:590:12", "type": { "tag": ":long" }, "value": 65522 },
{ "tag": "const", "name": "TB_KEY_HOME", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:591:12", "type": { "tag": ":long" }, "value": 65521 },
{ "tag": "const", "name": "TB_KEY_END", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:592:12", "type": { "tag": ":long" }, "value": 65520 },
{ "tag": "const", "name": "TB_KEY_F8", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:593:12", "type": { "tag": ":long" }, "value": 65528 },
{ "tag": "const", "name": "TB_KEY_F9", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:594:12", "type": { "tag": ":long" }, "value": 65527 },
{ "tag": "const", "name": "TB_KEY_F11", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:595:12", "type": { "tag": ":long" }, "value": 65525 },
{ "tag": "const", "name": "TB_KEY_F10", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:596:12", "type": { "tag": ":long" }, "value": 65526 },
{ "tag": "const", "name": "TB_KEY_F12", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:597:12", "type": { "tag": ":long" }, "value": 65524 },
{ "tag": "const", "name": "__USE_POSIX_IMPLICITLY", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:598:12", "type": { "tag": ":long" }, "value": 1 },
{ "tag": "const", "name": "_ATFILE_SOURCE", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:599:12", "type": { "tag": ":long" }, "value": 1 },
{ "tag": "const", "name": "_STDC_PREDEF_H", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:600:12", "type": { "tag": ":long" }, "value": 1 },
{ "tag": "const", "name": "__STDC_IEC_559__", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:601:12", "type": { "tag": ":long" }, "value": 1 },
{ "tag": "const", "name": "__STDC_ISO_10646__", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:602:12", "type": { "tag": ":long" }, "value": 201103 },
{ "tag": "const", "name": "__STDC_IEC_559_COMPLEX__", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:603:12", "type": { "tag": ":long" }, "value": 1 },
{ "tag": "const", "name": "__USE_POSIX", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:604:12", "type": { "tag": ":long" }, "value": 1 },
{ "tag": "const", "name": "__USE_POSIX2", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:605:12", "type": { "tag": ":long" }, "value": 1 },
{ "tag": "const", "name": "__USE_POSIX199309", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:606:12", "type": { "tag": ":long" }, "value": 1 },
{ "tag": "const", "name": "__USE_POSIX199506", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:607:12", "type": { "tag": ":long" }, "value": 1 },
{ "tag": "const", "name": "__USE_XOPEN2K", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:608:12", "type": { "tag": ":long" }, "value": 1 },
{ "tag": "const", "name": "__USE_XOPEN2K8", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:609:12", "type": { "tag": ":long" }, "value": 1 },
{ "tag": "const", "name": "__USE_MISC", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:610:12", "type": { "tag": ":long" }, "value": 1 },
{ "tag": "const", "name": "__USE_ATFILE", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:611:12", "type": { "tag": ":long" }, "value": 1 },
{ "tag": "const", "name": "__USE_FORTIFY_LEVEL", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:612:12", "type": { "tag": ":long" }, "value": 0 },
{ "tag": "const", "name": "__WORDSIZE", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:613:12", "type": { "tag": ":long" }, "value": 32 },
{ "tag": "const", "name": "TB_EOF", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:614:12", "type": { "tag": ":long" }, "value": -1 },
{ "tag": "const", "name": "_DEFAULT_SOURCE", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:615:12", "type": { "tag": ":long" }, "value": 1 },
{ "tag": "const", "name": "_POSIX_SOURCE", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:616:12", "type": { "tag": ":long" }, "value": 1 },
{ "tag": "const", "name": "_POSIX_C_SOURCE", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:617:12", "type": { "tag": ":long" }, "value": 200809 },
{ "tag": "const", "name": "UINT_LEAST32_MAX", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:618:21", "type": { "tag": ":unsigned-long" }, "value": 4294967295 },
{ "tag": "const", "name": "UINT_LEAST16_MAX", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:619:12", "type": { "tag": ":long" }, "value": 65535 },
{ "tag": "const", "name": "TB_OUTPUT_256", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:620:12", "type": { "tag": ":long" }, "value": 2 },
{ "tag": "const", "name": "INT_FAST8_MIN", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:621:12", "type": { "tag": ":long" }, "value": -128 },
{ "tag": "const", "name": "INT_FAST32_MIN", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:622:12", "type": { "tag": ":long" }, "value": -2147483648 },
{ "tag": "const", "name": "INT_FAST16_MIN", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:623:12", "type": { "tag": ":long" }, "value": -2147483648 },
{ "tag": "const", "name": "INT_FAST16_MAX", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:624:12", "type": { "tag": ":long" }, "value": 2147483647 },
{ "tag": "const", "name": "INT_FAST8_MAX", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:625:12", "type": { "tag": ":long" }, "value": 127 },
{ "tag": "const", "name": "TB_OUTPUT_GRAYSCALE", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:626:12", "type": { "tag": ":long" }, "value": 4 },
{ "tag": "const", "name": "INT_FAST32_MAX", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:627:12", "type": { "tag": ":long" }, "value": 2147483647 },
{ "tag": "const", "name": "UINT_FAST16_MAX", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:628:21", "type": { "tag": ":unsigned-long" }, "value": 4294967295 },
{ "tag": "const", "name": "UINT_FAST8_MAX", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:629:12", "type": { "tag": ":long" }, "value": 255 },
{ "tag": "const", "name": "TB_OUTPUT_NORMAL", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:630:12", "type": { "tag": ":long" }, "value": 1 },
{ "tag": "const", "name": "TB_INPUT_ESC", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:631:12", "type": { "tag": ":long" }, "value": 1 },
{ "tag": "const", "name": "TB_INPUT_CURRENT", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:632:12", "type": { "tag": ":long" }, "value": 0 },
{ "tag": "const", "name": "UINT_FAST32_MAX", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:633:21", "type": { "tag": ":unsigned-long" }, "value": 4294967295 },
{ "tag": "const", "name": "INTPTR_MIN", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:634:12", "type": { "tag": ":long" }, "value": -2147483648 },
{ "tag": "const", "name": "UINTPTR_MAX", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:635:21", "type": { "tag": ":unsigned-long" }, "value": 4294967295 },
{ "tag": "const", "name": "TB_INPUT_ALT", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:636:12", "type": { "tag": ":long" }, "value": 2 },
{ "tag": "const", "name": "__WCHAR_MIN", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:637:12", "type": { "tag": ":long" }, "value": -2147483648 },
{ "tag": "const", "name": "INTPTR_MAX", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:638:12", "type": { "tag": ":long" }, "value": 2147483647 },
{ "tag": "const", "name": "PTRDIFF_MIN", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:639:12", "type": { "tag": ":long" }, "value": -2147483648 },
{ "tag": "const", "name": "TB_INPUT_MOUSE", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:640:12", "type": { "tag": ":long" }, "value": 4 },
{ "tag": "const", "name": "SIG_ATOMIC_MAX", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:641:12", "type": { "tag": ":long" }, "value": 2147483647 },
{ "tag": "const", "name": "TB_HIDE_CURSOR", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:642:12", "type": { "tag": ":long" }, "value": -1 },
{ "tag": "const", "name": "SIG_ATOMIC_MIN", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:643:12", "type": { "tag": ":long" }, "value": -2147483648 },
{ "tag": "const", "name": "SIZE_MAX", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:644:21", "type": { "tag": ":unsigned-long" }, "value": 4294967295 },
{ "tag": "const", "name": "WCHAR_MAX", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:645:12", "type": { "tag": ":long" }, "value": 2147483647 },
{ "tag": "const", "name": "WCHAR_MIN", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:646:12", "type": { "tag": ":long" }, "value": -2147483648 },
{ "tag": "const", "name": "TB_EUNSUPPORTED_TERMINAL", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:647:12", "type": { "tag": ":long" }, "value": -1 },
{ "tag": "const", "name": "WINT_MIN", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:648:21", "type": { "tag": ":unsigned-long" }, "value": 0 },
{ "tag": "const", "name": "_BITS_WCHAR_H", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:649:12", "type": { "tag": ":long" }, "value": 1 },
{ "tag": "const", "name": "__WCHAR_MAX", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:650:12", "type": { "tag": ":long" }, "value": 2147483647 },
{ "tag": "const", "name": "PTRDIFF_MAX", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:651:12", "type": { "tag": ":long" }, "value": 2147483647 },
{ "tag": "const", "name": "TB_REVERSE", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:652:12", "type": { "tag": ":long" }, "value": 1024 },
{ "tag": "const", "name": "WINT_MAX", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:653:21", "type": { "tag": ":unsigned-long" }, "value": 4294967295 },
{ "tag": "const", "name": "TB_EVENT_KEY", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:654:12", "type": { "tag": ":long" }, "value": 1 },
{ "tag": "const", "name": "TB_EVENT_RESIZE", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:655:12", "type": { "tag": ":long" }, "value": 2 },
{ "tag": "const", "name": "TB_EFAILED_TO_OPEN_TTY", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:656:12", "type": { "tag": ":long" }, "value": -2 },
{ "tag": "const", "name": "TB_EVENT_MOUSE", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:657:12", "type": { "tag": ":long" }, "value": 3 },
{ "tag": "const", "name": "TB_RED", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:658:12", "type": { "tag": ":long" }, "value": 2 },
{ "tag": "const", "name": "TB_GREEN", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:659:12", "type": { "tag": ":long" }, "value": 3 },
{ "tag": "const", "name": "TB_YELLOW", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:660:12", "type": { "tag": ":long" }, "value": 4 },
{ "tag": "const", "name": "TB_BLUE", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:661:12", "type": { "tag": ":long" }, "value": 5 },
{ "tag": "const", "name": "TB_CYAN", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:662:12", "type": { "tag": ":long" }, "value": 7 },
{ "tag": "const", "name": "TB_WHITE", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:663:12", "type": { "tag": ":long" }, "value": 8 },
{ "tag": "const", "name": "INT8_MIN", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:664:12", "type": { "tag": ":long" }, "value": -128 },
{ "tag": "const", "name": "INT16_MIN", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:665:12", "type": { "tag": ":long" }, "value": -32768 },
{ "tag": "const", "name": "TB_MAGENTA", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:666:12", "type": { "tag": ":long" }, "value": 6 },
{ "tag": "const", "name": "INT32_MIN", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:667:12", "type": { "tag": ":long" }, "value": -2147483648 },
{ "tag": "const", "name": "TB_KEY_CTRL_7", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:668:12", "type": { "tag": ":long" }, "value": 31 },
{ "tag": "const", "name": "INT8_MAX", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:669:12", "type": { "tag": ":long" }, "value": 127 },
{ "tag": "const", "name": "TB_KEY_CTRL_SLASH", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:670:12", "type": { "tag": ":long" }, "value": 31 },
{ "tag": "const", "name": "TB_KEY_CTRL_UNDERSCORE", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:671:12", "type": { "tag": ":long" }, "value": 31 },
{ "tag": "const", "name": "TB_BOLD", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:672:12", "type": { "tag": ":long" }, "value": 256 },
{ "tag": "const", "name": "INT16_MAX", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:673:12", "type": { "tag": ":long" }, "value": 32767 },
{ "tag": "const", "name": "TB_KEY_SPACE", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:674:12", "type": { "tag": ":long" }, "value": 32 },
{ "tag": "const", "name": "INT32_MAX", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:675:12", "type": { "tag": ":long" }, "value": 2147483647 },
{ "tag": "const", "name": "TB_KEY_BACKSPACE2", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:676:12", "type": { "tag": ":long" }, "value": 127 },
{ "tag": "const", "name": "UINT16_MAX", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:677:12", "type": { "tag": ":long" }, "value": 65535 },
{ "tag": "const", "name": "UINT8_MAX", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:678:12", "type": { "tag": ":long" }, "value": 255 },
{ "tag": "const", "name": "UINT32_MAX", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:679:21", "type": { "tag": ":unsigned-long" }, "value": 4294967295 },
{ "tag": "const", "name": "TB_MOD_ALT", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:680:12", "type": { "tag": ":long" }, "value": 1 },
{ "tag": "const", "name": "TB_KEY_CTRL_8", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:681:12", "type": { "tag": ":long" }, "value": 127 },
{ "tag": "const", "name": "TB_BLACK", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:682:12", "type": { "tag": ":long" }, "value": 1 },
{ "tag": "const", "name": "TB_DEFAULT", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:683:12", "type": { "tag": ":long" }, "value": 0 },
{ "tag": "const", "name": "INT_LEAST8_MIN", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:684:12", "type": { "tag": ":long" }, "value": -128 },
{ "tag": "const", "name": "TB_UNDERLINE", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:685:12", "type": { "tag": ":long" }, "value": 512 },
{ "tag": "const", "name": "INT_LEAST16_MIN", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:686:12", "type": { "tag": ":long" }, "value": -32768 },
{ "tag": "const", "name": "TB_EPIPE_TRAP_ERROR", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:687:12", "type": { "tag": ":long" }, "value": -3 },
{ "tag": "const", "name": "INT_LEAST32_MIN", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:688:12", "type": { "tag": ":long" }, "value": -2147483648 },
{ "tag": "const", "name": "INT_LEAST16_MAX", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:689:12", "type": { "tag": ":long" }, "value": 32767 },
{ "tag": "const", "name": "INT_LEAST8_MAX", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:690:12", "type": { "tag": ":long" }, "value": 127 },
{ "tag": "const", "name": "TB_OUTPUT_CURRENT", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:691:12", "type": { "tag": ":long" }, "value": 0 },
{ "tag": "const", "name": "INT_LEAST32_MAX", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:692:12", "type": { "tag": ":long" }, "value": 2147483647 },
{ "tag": "const", "name": "TB_KEY_CTRL_RSQ_BRACKET", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:693:12", "type": { "tag": ":long" }, "value": 29 },
{ "tag": "const", "name": "TB_OUTPUT_216", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:694:12", "type": { "tag": ":long" }, "value": 3 },
{ "tag": "const", "name": "UINT_LEAST8_MAX", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:695:12", "type": { "tag": ":long" }, "value": 255 },
{ "tag": "const", "name": "TB_KEY_CTRL_6", "location": "/home/grant/code/whetstone/termbox.i686-pc-linux-gnu.h:696:12", "type": { "tag": ":long" }, "value": 30 }
]
